version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Creating environment file...
      - printf "VITE_API_BASE_URL=%s\nVITE_AWS_REGION=%s\nVITE_COGNITO_USER_POOL_ID=%s\nVITE_COGNITO_CLIENT_ID=%s\n" "$VITE_API_BASE_URL" "$VITE_AWS_REGION" "$VITE_COGNITO_USER_POOL_ID" "$VITE_COGNITO_CLIENT_ID" > .env
      - echo "Sanity check - .env contents (redacted):"
      - grep -v "CLIENT_ID" .env | grep -v "USER_POOL_ID" || echo "Env file created"
      - echo Building application...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
cache:
  paths:
    - 'node_modules/**/*'
